[마켓컬리] 상품 view.py
wecode-bootcamp-korea/24-1st-WoowahanSiblings-backend pull request #5
Opened 2021-09-03 10:14 UTC by kohys92

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- product POST 
- product GET 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-03 10:23 UTC, kohys92 commented
![Screen Shot 2021-09-03 at 7 13 09 PM](https://user-images.githubusercontent.com/36935693/131990617-45476aa6-4c7b-4a7f-90b0-1612c247c1e1.png)

2021-09-03 12:56 UTC, S2-J1NG requested changes

2021-09-03 12:56 UTC, S2-J1NG commented on bbmarket/urls.py
> +    path('bbmarket', include('products.urls')),
app 에 맞는 url `path` 지정해주세요~!
이런 경우 `bbmarket` 으로 `users` APP 으로 갈지 `product` APP으로 갈지 장고가 파악하지 못 합니다.

아래 처럼 각 앱 이름을  path에 적을 수도 있습니다.
```
path('users', include('users.urls'),
path('products', include('products.urls')
```

2021-09-03 12:56 UTC, S2-J1NG commented on products/views.py
> +    def post(self, request):
`product` 를 유저가 직접 등록하는 경우가 있나요??

2021-09-03 12:57 UTC, S2-J1NG commented
conflict 해결해주세요!
`db_uploader `와 `.csv` 파일은 `github`에 올라오면 안 됩니다. `.gitignore`에 추가 해주시고 올라온 파일은 삭제해주세요
데이터가 있는 파일이기 때문에 외부에 공개되서는 안 됩니다.

2021-09-04 02:06 UTC, S2-J1NG commented
conflict 해결해주세요~

2021-09-04 04:16 UTC, kohys92 commented on bbmarket/urls.py
> +    path('bbmarket', include('products.urls')),
말씀하신대로 path 수정했습니다! 
`path('users', include('users.urls'),
path('products', include('products.urls')`

2021-09-04 04:22 UTC, kohys92 commented on products/views.py
> +    def post(self, request):
product 를 유저가 직접 등록하는 경우는 없어서 POST method 지웠습니다!

2021-09-04 04:28 UTC, kohys92 commented
> conflict 해결해주세요~

conflict 해결했습니다~

2021-09-04 05:03 UTC, kohys92 commented
![Screen Shot 2021-09-04 at 1 47 04 PM](https://user-images.githubusercontent.com/36935693/132083152-f0119426-ac10-4a06-9802-caf14794da95.png)

![Screen Shot 2021-09-04 at 1 47 29 PM](https://user-images.githubusercontent.com/36935693/132083155-c367b76b-438b-4e21-b982-288d81e134ef.png)

2021-09-05 00:39 UTC, S2-J1NG requested changes

2021-09-05 00:39 UTC, S2-J1NG commented on products/views.py
> +            products = Product.objects.all()
최근 등록 순 혹은 인기 상품 순 등 정렬 순서 없이 상품 리스트를 전달하기로 프론트와 상의 하셨나요??

2021-09-05 00:39 UTC, S2-J1NG commented on products/views.py
> +from datetime import datetime
로직에서 사용하고 있지 않는 내용은 제외 시켜주세요

2021-09-05 00:39 UTC, S2-J1NG commented on products/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
keyerror 외에 발생할 에러 찾아서 추가 해주세요~!

2021-09-06 02:36 UTC, kohys92 commented on products/views.py
> +            products = Product.objects.all()
최근 등록 순, 인기 상품 순 등 정렬 순서는 추가 기능으로 하기로 상의가 되었습니다. 일단 현재는 카테고리별로 순서없이 상품리스트를 전달하고 있습니다.

2021-09-06 03:00 UTC, kohys92 commented on products/views.py
> +from datetime import datetime
넵 지웠습니다!

2021-09-06 04:02 UTC, kohys92 commented on products/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
KEY_ERROR가 발생할 경우가 없어서 지웠습니다. 그리고 데이터베이스에 상품이 없는 경우에 예외처리를 로직으로 처리해주었습니다!

2021-09-06 08:47 UTC, S2-J1NG commented
정렬 기능 추가로 브랜치 생성해서 진행 해주세요!
수고하셨습니다~!

2021-09-06 08:48 UTC, merged