[마켓컬리] Cart View 기능 분리
wecode-bootcamp-korea/24-1st-WoowahanSiblings-backend pull request #8
Opened 2021-09-07 05:59 UTC by Oraange

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- cart(장바구니)기능만 따로 분리하였습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- orders앱의 view파일에서 cart 관련한 로직만 브랜치 따로 만들었습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 08:10 UTC, kst6294 commented on orders/views.py
> +
```suggestion
            if not Cart.objects.filter(user_id= user_id, product_id = product_id):
                return "없어요"

            cart, is_created = Cart.objects.get_or_create(product_id = product_id, user_id = user_id)
            
            if is_created:
                return "성공"
                
           cart.purchase_quantity += purchase_quantity
           cart.save()

```

2021-09-07 08:10 UTC, kst6294 commented on orders/views.py
> +
```suggestion
            cart, is_created = Cart.objects.update_or_create(product_id = product_id, user_id = user_id, defaults = { 'purchase_quantity' : cart.purchase.quantity + int(purchase_quantity) })

```

2021-09-07 10:47 UTC, kst6294 requested changes

2021-09-07 10:47 UTC, kst6294 commented on orders/views.py
> +            Cart.objects.update_or_create(product_id = product_id, user_id = user_id, defaults = { 'purchase_quantity' : int(current_quantity) + int(purchase_quantity) })
이부분에서 Cart 가 존재하지 않는 경우, update_or_create 동작할 때 current_quantity 확인해주세요!

2021-09-08 02:04 UTC, S2-J1NG requested changes

2021-09-08 02:04 UTC, S2-J1NG commented on orders/views.py
> +                current_product.purchase_quantity = current_product_quantity + int(purchase_quantity)
`current_product.purchase_quantity += int(purchase_quantity)` 로 코드 줄일 수 있습니다

2021-09-08 04:18 UTC, Oraange commented on orders/views.py
> +                current_product.purchase_quantity = current_product_quantity + int(purchase_quantity)
수정했습니다!!!

2021-09-08 07:30 UTC, S2-J1NG commented
데코레이터 주석으로 처리한 이유가 있을까요??

2021-09-08 07:59 UTC, Oraange commented
수정했습니다 ㅠㅠ

2021-09-08 08:30 UTC, merged